name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        run: docker run hello-world
      - name: Stop all containers
        run: docker container stop $(docker container ls -aq)
      - name: Remove all containers
        run: docker rm -f $(docker ps -a -q)
      - name: Remove all images
        run: docker rmi -f $(docker image ls)
      - name: Build the stack
        run: docker-compose up -d --force-recreate
      - name: Test
        run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
